# Selecting a specific group from a dataframe
To select a specific group, we will be using the get_group method after applying groupby on a statsbomb DataFrame.

In [1]:
"""



LinkedIn: Sara Bentelli
Twitter: @SoccerbyNumber6


Wishing you the best of luck!



"""

import pandas as pd
from mplsoccer import Sbopen
parser = Sbopen()

In [2]:
# Load the competitions 

df_competition= parser.competition()
df_competition

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2023-12-12T07:43:33.436182,None,None,2023-12-12T07:43:33.436182
1,16,4,Europe,Champions League,male,False,False,2018/2019,2023-03-07T12:20:48.118250,2021-06-13T16:17:31.694,None,2023-03-07T12:20:48.118250
2,16,1,Europe,Champions League,male,False,False,2017/2018,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-01-23T21:55:30.425330
3,16,2,Europe,Champions League,male,False,False,2016/2017,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
4,16,27,Europe,Champions League,male,False,False,2015/2016,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
...,...,...,...,...,...,...,...,...,...,...,...,...
65,55,43,Europe,UEFA Euro,male,False,True,2020,2023-02-24T21:26:47.128979,2023-04-27T22:38:34.970148,2023-04-27T22:38:34.970148,2023-02-24T21:26:47.128979
66,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2023-06-18T19:28:39.443883,2021-06-13T16:17:31.694,None,2023-06-18T19:28:39.443883
67,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2023-10-24T03:36:54.066267,2023-10-24T03:37:29.085948,2023-10-24T03:37:29.085948,2023-10-24T03:36:54.066267
68,72,107,International,Women's World Cup,female,False,True,2023,2023-12-12T14:06:50.626363,2023-12-12T14:12:41.561162,2023-12-12T14:12:41.561162,2023-12-12T14:06:50.626363
69,72,30,International,Women's World Cup,female,False,True,2019,2023-07-27T10:33:48.273734,2021-06-13T16:17:31.694,None,2023-07-27T10:33:48.273734

In [3]:
# Bundesliga 2015/2016 has competition id 9, and season id 27
#Load the list of matches for this competition

matches=parser.match(competition_id=9,season_id=27)
matches

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,competition_stage_id,competition_stage_name,stadium_id,stadium_name,stadium_country_id,stadium_country_name,referee_id,referee_name,referee_country_id,referee_country_name
0,3890561,2016-05-14,2016-05-14 15:30:00,1,4,available,unscheduled,2023-07-24 07:47:12.510532,NaT,34,...,1,Regular Season,4541,PreZero Arena,85,Germany,186,Felix Brych,85,Germany
1,3890505,2016-04-02,2016-04-02 15:30:00,1,0,available,unscheduled,2023-08-03 13:14:14.503553,NaT,28,...,1,Regular Season,4867,Allianz Arena,85,Germany,1008758,Florian Meyer,85,Germany
2,3890511,2016-04-08,2016-04-08 20:30:00,2,2,available,unscheduled,2023-08-06 05:50:38.345688,NaT,29,...,1,Regular Season,367,Olympiastadion Berlin,85,Germany,235,Benjamin Brand,85,Germany
3,3890515,2016-04-09,2016-04-09 15:30:00,1,2,available,unscheduled,2023-07-18 17:52:17.363623,NaT,29,...,1,Regular Season,379,Volksparkstadion,85,Germany,1008767,Peter Sippel,85,Germany
4,3890411,2015-12-20,2015-12-20 16:30:00,2,0,available,unscheduled,2023-07-16 13:47:06.565811,NaT,17,...,1,Regular Season,367,Olympiastadion Berlin,85,Germany,1008767,Peter Sippel,85,Germany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,3890263,2015-08-15,2015-08-15 15:30:00,0,1,available,unscheduled,2023-07-12 21:36:52.313207,NaT,1,...,1,Regular Season,374,Mewa Arena,85,Germany,227,Guido Winkmann,85,Germany
302,3890262,2015-08-15,2015-08-15 15:30:00,2,2,available,unscheduled,2023-07-13 06:06:10.566448,NaT,1,...,1,Regular Season,548,Merck-Stadion am BÃ¶llenfalltor,85,Germany,186,Felix Brych,85,Germany
303,3890261,2015-08-15,2015-08-15 18:30:00,4,0,available,unscheduled,2023-07-12 02:09:30.607244,NaT,1,...,1,Regular Season,373,Signal-Iduna-Park,85,Germany,229,Tobias Stieler,85,Germany
304,3890260,2015-08-15,2015-08-15 15:30:00,2,1,available,unscheduled,2023-07-11 19:49:42.336088,NaT,1,...,1,Regular Season,377,BayArena,85,Germany,244,Robert Hartmann,85,Germany
305,3890259,2015-08-14,2015-08-14 20:30:00,5,0,available,unscheduled,2023-07-11 01:43:28.460567,NaT,1,...,1,Regular Season,4867,Allianz Arena,85,Germany,245,Bastian Dankert,85,Germany

In [4]:
#Look inside matches, I'll take only the needed columns 

matches=matches[['home_team_name','away_team_name','home_score','away_score','match_id','match_date']]
matches

,home_team_name,away_team_name,home_score,away_score,match_id,match_date
0,Hoffenheim,Schalke 04,1,4,3890561,2016-05-14
1,Bayern Munich,Eintracht Frankfurt,1,0,3890505,2016-04-02
2,Hertha Berlin,Hannover 96,2,2,3890511,2016-04-08
3,Hamburger SV,Darmstadt 98,1,2,3890515,2016-04-09
4,Hertha Berlin,FSV Mainz 05,2,0,3890411,2015-12-20
...,...,...,...,...,...,...
301,FSV Mainz 05,Ingolstadt,0,1,3890263,2015-08-15
302,Darmstadt 98,Hannover 96,2,2,3890262,2015-08-15
303,Borussia Dortmund,Borussia MÃ¶nchengladbach,4,0,3890261,2015-08-15
304,Bayer Leverkusen,Hoffenheim,2,1,3890260,2015-08-15
305,Bayern Munich,Hamburger SV,5,0,3890259,2015-08-14

In [5]:
# I will choose the match  Borussia Dortmund VS Borussia MÃ¶nchengladbach 
# The ID of this match is 3890261.

# we open the data event [0]
data=parser.event(3890261)[0]
data

,id,index,period,timestamp,minute,second,possession,duration,match_id,type_id,...,foul_committed_advantage,foul_won_advantage,shot_open_goal,block_save_block,pass_cut_back,substitution_replacement_id,substitution_replacement_name,block_deflection,foul_committed_card_id,foul_committed_card_name
0,2d880d36-d8dc-4eea-a884-4b96e4268838,1,1,00:00:00,0,0,1,0.000000,3890261,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a05941c3-35d8-4e6c-8349-d350c565fd64,2,1,00:00:00,0,0,1,0.000000,3890261,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7eb792bb-f438-4f15-bd71-10da02b4cf78,3,1,00:00:00,0,0,1,0.000000,3890261,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,058647ed-b252-48f1-90f0-f44dd06aa5c2,4,1,00:00:00,0,0,1,0.000000,3890261,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,e6907bbb-ea91-4c43-804d-50eda2956349,5,1,00:00:00.382000,0,0,2,0.474220,3890261,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4265,63b39bda-7146-40cd-8d28-746e71216f53,4266,2,00:44:59.151000,89,59,173,NaN,3890261,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4266,055652c4-3709-43ab-90fe-decaf2e0bca6,4267,2,00:44:59.151000,89,59,173,0.002066,3890261,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4267,b9521c0f-daf9-4d56-ad0e-007da552bfa8,4268,2,00:44:59.153000,89,59,173,1.129476,3890261,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4268,4538c0e5-4867-4cfc-90b1-2ac10213c76c,4269,2,00:45:03.941000,90,3,173,0.000000,3890261,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4269,d42d9431-8b61-48fe-a902-47b46478ad61,4270,2,00:45:03.941000,90,3,173,0.000000,3890261,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Group the DataFrame based on the 'type_name' column.

grouped_data=data.groupby("type_name")

#Determining the count of groups.

grouped_data.ngroups

27

In [7]:
# We have 27 groups (27 Types)
# I will select the group of shots
# type_name== Shot

selected_group=grouped_data.get_group('Shot')

# Selecting only the important columns on the selected group

selected_group[["x",'y','end_x','end_y','player_name','match_id',"id","type_name","outcome_name","minute",'second',"under_pressure",'shot_statsbomb_xg']]

,x,y,end_x,end_y,player_name,match_id,id,type_name,outcome_name,minute,second,under_pressure,shot_statsbomb_xg
237,114.6,31.6,115.1,32.2,Josip Drmic,3890261,3bda18c4-ba48-410d-9537-7a9bc9f78296,Shot,Blocked,4,18,NaN,0.060656
242,99.6,41.7,108.3,42.6,Granit Xhaka,3890261,2e45035e-c4bd-4e43-b43f-d6055a4be720,Shot,Blocked,4,21,NaN,0.039256
246,107.6,44.8,120.0,42.5,Tony Jantschke,3890261,0b46df84-cdba-46c3-9c16-2fd3a4f86265,Shot,Off T,4,21,1.0,0.062318
651,111.4,41.1,120.0,42.3,Sokratis Papastathopoulos,3890261,48677f28-7ae1-41d1-98e2-03c45633f090,Shot,Off T,12,49,1.0,0.061370
701,105.6,26.5,120.0,38.9,Marco Reus,3890261,5d25340e-07b7-4785-91b5-93462ce8f315,Shot,Goal,14,5,1.0,0.067917
980,87.5,45.1,96.7,44.5,Ä°lkay GÃ¼ndoÄŸan,3890261,8e208918-c3bd-494e-99aa-77e502b5a568,Shot,Blocked,20,1,NaN,0.026441
1015,108.7,34.9,120.0,42.7,Pierre-Emerick Aubameyang,3890261,ba78e418-fb56-462a-a94b-c745ec83b116,Shot,Goal,20,33,NaN,0.052489
1402,91.6,32.1,120.0,34.1,Henrikh Mkhitaryan,3890261,954c6793-f1fc-4803-a2db-c71f4da5887d,Shot,Off T,29,17,NaN,0.031739
1608,113.9,33.7,120.0,42.7,Henrikh Mkhitaryan,3890261,bb618c07-d2a3-41c4-b45e-df2a339cacf7,Shot,Goal,32,30,NaN,0.958727
1703,109.2,40.3,111.7,40.6,Pierre-Emerick Aubameyang,3890261,f6353a98-b015-46bb-be79-a8f94e99fd4e,Shot,Blocked,35,0,1.0,0.096489
1709,110.6,35.4,119.2,36.9,Mats Hummels,3890261,b7d2da0f-1729-4b88-9a6e-e18264edae56,Shot,Blocked,35,38,1.0,0.045515
1713,100.8,24.7,110.0,35.3,Pierre-Emerick Aubameyang,3890261,7979bc48-5136-46ca-82ff-7c307075baad,Shot,Blocked,35,40,NaN,0.017484
1718,111.8,23.2,108.1,80.0,Marco Reus,3890261,e95ee1e2-9b43-4da5-b157-a33a76cd9a59,Shot,Wayward,35,42,NaN,0.034037
1831,99.0,27.5,120.0,47.3,Henrikh Mkhitaryan,3890261,0fc440ba-f116-4162-973e-e199cc8d1b52,Shot,Off T,37,56,NaN,0.028271
1981,84.5,42.7,116.0,42.0,Sokratis Papastathopoulos,3890261,b360929d-0ebf-418c-b2b5-496d15b6cce1,Shot,Saved,41,11,NaN,0.013793
2336,94.3,50.0,120.0,34.7,Josip Drmic,3890261,793e2d0b-4412-4ee5-8b50-6134224d031b,Shot,Off T,48,11,NaN,0.039503
2362,107.1,39.5,120.0,37.1,Henrikh Mkhitaryan,3890261,431a100b-2e24-4ab7-9d12-af0bdf5508d5,Shot,Goal,49,16,NaN,0.272696
2726,107.8,42.3,118.4,39.9,Granit Xhaka,3890261,2b5f1ec3-a543-49be-a7de-6a829a1dfdc7,Shot,Saved,56,24,1.0,0.040418
3163,105.6,36.2,120.0,35.2,Shinji Kagawa,3890261,66586d90-365f-404a-983e-061c8dcb3f9d,Shot,Off T,65,30,NaN,0.208124
3901,96.5,41.9,120.0,43.6,Julian Weigl,3890261,f3f46616-174b-4797-9fd5-88be838d9546,Shot,Off T,83,45,NaN,0.030190
4079,94.0,33.8,117.5,42.0,Ä°lkay GÃ¼ndoÄŸan,3890261,f09e0459-000e-496f-b3f9-37cb762f30a9,Shot,Saved,86,57,1.0,0.027960

In [8]:
# Wish me luck!